
default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  username:
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: lovevery_development

test:
  <<: *default
  database: lovevery_test

production:
  <<: *default
  database: lovevery_production
